openapi: 3.0.3
info:
  description: |
    <h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>
  title: Synctera API
  version: 0.5.0
servers:
- description: Production
  url: https://api.synctera.com/v0
- description: Sandbox (no real world financial impact)
  url: https://api.sandbox.synctera.com/v0
security:
- bearerAuth: []
tags:
- description: Request to create a new sandbox user
  name: Signup
paths:
  /signups:
    description: |
      An endpoint for creating the necessary tenant objects when signing up a new sandbox user.  This API should be considered temporary and will likely be replaced.
    post:
      description: |
        Create a bank, partner and party for a new sandbox user
      operationId: createSignup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/signup_input'
        description: Signup input data
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/signup_ids'
          description: Successful signup
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: BadRequest
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
      summary: Signup a new sandbox user
      tags:
      - Signup
    summary: Signups
components:
  responses:
    bad_request:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: BadRequest
    unauthorized:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: Unauthorized
  schemas:
    signup_input:
      description: Signup input values
      properties:
        bank_name:
          description: Bank Name
          readOnly: true
          type: string
        bank_short_code:
          description: Bank Short Code
          readOnly: true
          type: string
        partner_name:
          description: Partner Name
          readOnly: true
          type: string
        user_id:
          description: Bank's party's user_id
          readOnly: true
          type: string
      required:
      - bank_name
      - bank_short_code
      - partner_name
      - user_id
      title: Signup input values
      type: object
    signup_ids:
      description: Signup output names
      example:
        party_uuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        party_user_id: 1
        partner_id: 6
        bank_id: 0
      properties:
        bank_id:
          description: Bank ID
          type: integer
        partner_id:
          description: Partner ID
          type: integer
        party_user_id:
          description: Bank's party's party_user_id
          type: integer
        party_uuid:
          description: Party UUIID
          format: uuid
          type: string
      required:
      - bank_id
      - partner_id
      - party_user_id
      - party_uuid
      title: Signup output names
      type: object
    error:
      properties:
        error_details:
          description: Detailed description of error
          example: faker.lorem.sentence
          type: string
      title: Error
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: private_key
      scheme: bearer
      type: http
