openapi: 3.0.3
info:
  description: |
    <h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>
  title: Synctera API
  version: 0.5.0
servers:
- description: Production
  url: https://api.synctera.com/v0
- description: Sandbox (no real world financial impact)
  url: https://api-sandbox.synctera.com/v0
security:
- bearerAuth: []
tags:
- description: Requests to create and manage reconciliation
  name: Reconciliations
paths:
  /reconciliations:
    description: |
      The Reconcilations collections represents the jobs reconciling transactions.
    get:
      description: Retrieves paginated list of reconciliations
      operationId: listReconciliations
      parameters:
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 100
          description: Maximum of objects to return per page
          example: 100
          minimum: 1
          type: integer
        style: form
      - explode: true
        in: query
        name: page_token
        required: false
        schema:
          description: Optional pagination token to be provided to retrieve subsequent
            pages, returned from previous get
          example: faker.random.alphaNumeric(10)
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                allOf:
                - properties:
                    reconciliations:
                      description: Array of reconciliations
                      items:
                        $ref: '#/components/schemas/reconciliation'
                      type: array
                  type: object
                - $ref: '#/components/schemas/paginated_response'
          description: List of reconciliations
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Forbidden error
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: List reconciliations
      tags:
      - Reconciliations
    post:
      description: |
        Create a new reconciliation job
      operationId: createReconciliation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/reconciliation_input'
        description: Reconciliation to perform
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reconciliation'
          description: Successful creation of a reconciliation
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: BadRequest
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Forbidden error
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: Create a reconciliation
      tags:
      - Reconciliations
    summary: Reconciliations
  /reconciliations/{reconciliation_id}:
    description: |
      The Reconcilations collections represents the jobs reconciling transactions.
    get:
      description: Retrieves one reconciliation by id
      operationId: getReconciliation
      parameters:
      - description: Reconciliation id
        explode: false
        in: path
        name: reconciliation_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reconciliation'
          description: Successful retrieval of a reconciliation
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: BadRequest
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Resource not found
      summary: Get reconciliation
      tags:
      - Reconciliations
    summary: Reconciliation by ID
components:
  parameters:
    limit:
      explode: true
      in: query
      name: limit
      required: false
      schema:
        default: 100
        description: Maximum of objects to return per page
        example: 100
        minimum: 1
        type: integer
      style: form
    page_token:
      explode: true
      in: query
      name: page_token
      required: false
      schema:
        description: Optional pagination token to be provided to retrieve subsequent
          pages, returned from previous get
        example: faker.random.alphaNumeric(10)
        type: string
      style: form
    reconciliation_id:
      description: Reconciliation id
      explode: false
      in: path
      name: reconciliation_id
      required: true
      schema:
        format: uuid
        type: string
      style: simple
  responses:
    unauthorized:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: Unauthorized
    forbidden:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: Forbidden error
    internal_server_error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: Internal server error
    bad_request:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: BadRequest
    not_found:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: Resource not found
  schemas:
    ingestion_status:
      description: Reconciliation ingestion status values
      enum:
      - IN_PROCESS
      - COMPLETED
      - FAILED
      title: Reconciliation Ingestion Status Values
      type: string
    reconciliation:
      description: Reconciliation
      example:
        file_name: faker.random.alphaNumeric(14)
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        id:
          description: Reconciliation ID
          format: uuid
          readOnly: true
          type: string
        file_name:
          description: Filename of the data to be reconciled
          example: faker.random.alphaNumeric(14)
          readOnly: true
          type: string
        ingestion_status:
          $ref: '#/components/schemas/ingestion_status'
      required:
      - file_name
      - id
      - ingestion_status
      title: Reconciliation
      type: object
    paginated_response:
      properties:
        next_page_token:
          description: If returned, use the next_page_token to query for the next
            page of results.
          example: faker.random.alphaNumeric(10)
          type: string
      title: Paginated List response
      type: object
    error:
      properties:
        error_details:
          description: Detailed description of error
          example: faker.lorem.sentence
          type: string
      title: Error
      type: object
    reconciliation_input:
      description: Input data for a reconciliation
      properties:
        file_name:
          description: Filename of the data to be reconciled
          example: faker.random.alphaNumeric(14)
          type: string
        byte_data:
          description: Base64url encoded image
          format: byte
          type: string
      required:
      - byte_data
      - file_name
      title: Reconciliation Input
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: api_key
      scheme: bearer
      type: http
