openapi: 3.0.3
info:
  description: |
    <h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>
  title: Synctera API
  version: 0.5.0
servers:
- description: Production
  url: https://api.synctera.com/v0
- description: Sandbox (no real world financial impact)
  url: https://api-sandbox.synctera.com/v0
security:
- bearerAuth: []
tags:
- description: |
    The Disclosures resource is used to track the status of disclosures and
    ensure that customers have been shown the necessary disclosures to meet
    regulatory obligations.
  name: Disclosures
paths:
  /customers/{customer_id}/disclosures:
    description: |
      Disclosures to be made to customers
    get:
      description: Retrieves paginated list of disclosures associated with the authorized
        requester
      operationId: listDisclosures
      parameters:
      - description: Customer ID
        explode: false
        in: path
        name: customer_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 100
          description: Maximum of objects to return per page
          example: 100
          minimum: 1
          type: integer
        style: form
      - explode: true
        in: query
        name: page_token
        required: false
        schema:
          description: Optional pagination token to be provided to retrieve subsequent
            pages, returned from previous get
          example: faker.random.alphaNumeric(10)
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/disclosure_response'
          description: List of disclosures
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Forbidden error
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: List Disclosures
      tags:
      - Disclosures
    post:
      description: |
        Disclosures to be made to customers
      operationId: createDisclosure
      parameters:
      - description: Customer ID
        explode: false
        in: path
        name: customer_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/disclosure'
        description: Disclosure to create
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/disclosure'
          description: Created disclosure
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: BadRequest
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Forbidden error
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal server error
      summary: Create a Disclosure
      tags:
      - Disclosures
    summary: Disclosures
components:
  parameters:
    customer_id:
      description: Customer ID
      explode: false
      in: path
      name: customer_id
      required: true
      schema:
        format: uuid
        type: string
      style: simple
    limit:
      explode: true
      in: query
      name: limit
      required: false
      schema:
        default: 100
        description: Maximum of objects to return per page
        example: 100
        minimum: 1
        type: integer
      style: form
    page_token:
      explode: true
      in: query
      name: page_token
      required: false
      schema:
        description: Optional pagination token to be provided to retrieve subsequent
          pages, returned from previous get
        example: faker.random.alphaNumeric(10)
        type: string
      style: form
  responses:
    unauthorized:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: Unauthorized
    forbidden:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: Forbidden error
    internal_server_error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: Internal server error
    bad_request:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: BadRequest
  schemas:
    disclosure:
      description: Represents a disclosure
      example:
        creation_time: 2021-05-01T23:59:59Z
        event_type: VIEWED
        last_updated_time: 2021-05-01T23:59:59Z
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        type: REG_DD
        version: "1.1"
        timestamp: 2021-05-01T23:59:59Z
      properties:
        id:
          description: Disclosure ID
          format: uuid
          type: string
        type:
          description: Disclosure Type
          enum:
          - REG_DD
          - KYC_DATA_COLLECTION
          - REG_E
          example: REG_DD
          type: string
        version:
          description: Disclosure Version
          example: "1.1"
          type: string
        timestamp:
          description: Date of disclosure
          example: 2021-05-01T23:59:59Z
          format: date-time
          type: string
        creation_time:
          example: 2021-05-01T23:59:59Z
          format: date-time
          readOnly: true
          type: string
        last_updated_time:
          example: 2021-05-01T23:59:59Z
          format: date-time
          readOnly: true
          type: string
        event_type:
          enum:
          - DISPLAYED
          - VIEWED
          - ACKNOWLEDGED
          example: VIEWED
          type: string
      required:
      - timestamp
      - type
      - version
      title: Disclosure
      type: object
    disclosure_response:
      description: Represents all customer disclosures
      example:
        disclosures:
        - creation_time: 2021-05-01T23:59:59Z
          event_type: VIEWED
          last_updated_time: 2021-05-01T23:59:59Z
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          type: REG_DD
          version: "1.1"
          timestamp: 2021-05-01T23:59:59Z
        - creation_time: 2021-05-01T23:59:59Z
          event_type: VIEWED
          last_updated_time: 2021-05-01T23:59:59Z
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          type: REG_DD
          version: "1.1"
          timestamp: 2021-05-01T23:59:59Z
      properties:
        disclosures:
          description: List of the customer's disclosures
          items:
            $ref: '#/components/schemas/disclosure'
          type: array
      title: List of Customer Disclosures
      type: object
    error:
      properties:
        error_details:
          description: Detailed description of error
          example: faker.lorem.sentence
          type: string
      title: Error
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: api_key
      scheme: bearer
      type: http
